export const spaceBuds = {
  0: {
    name: 'SpaceBud #0',
    traits: ['Star Suit', 'Chestplate', 'Belt', 'Covered Helmet'],
    image: 'ipfs://QmNyHUZxfRxGpwg9QSbe3cMDkaT8so17TRvzXpNio5gbGf',
    type: 'Frog',
    arweaveId: '4zXmWOWjzVZUCoEzhIzy7iCg2xs_EkdCvT0I6TYOoGg',
  },
  1: {
    name: 'SpaceBud #1',
    traits: ['Chestplate', 'Covered Helmet', 'Revolver', 'Sword'],
    image: 'ipfs://QmarLwYwUyT4TsBk8g6c4DkJV6QoauF6chagY1xJDByUfH',
    type: 'Frog',
    arweaveId: 't1C-3xL_0vcvj5Ifw_ue_PLamad59xTCeogyApQLaTQ',
  },
  2: {
    name: 'SpaceBud #2',
    traits: ['Chestplate', 'Belt', 'Ski Goggles', 'Wool Boots'],
    image: 'ipfs://QmWZF3FwNBvJAjnQP8LzNdBzmUdKJhwDRgyhTV8mStyj8G',
    type: 'Alien',
    arweaveId: 'Z3yClDdakjo1nrw02_YdustNJjGp8UojOKpc-nNb74A',
  },
  3: {
    name: 'SpaceBud #3',
    traits: ['Chestplate', 'Belt', 'SPO'],
    image: 'ipfs://QmToz6Vgff4LNqxnZEBvy1JyVpDVxgZGvRMvjJLpSZqkGJ',
    type: 'Frog',
    arweaveId: 'W1NMCaWIvPPNo7d-a7515v4VrHNx1XgYmTDFzDxbUTU',
  },
  4: {
    name: 'SpaceBud #4',
    traits: [
      'Special Background',
      'Chestplate',
      'Belt',
      'Covered Helmet',
      'X-Ray',
    ],
    image: 'ipfs://QmdJGaN3xstZmFEUC8MySy1LTM3sckCfx7We2ca94EFMBs',
    type: 'Ape',
    arweaveId: 'oX7MuIT63_8fNq4iYvnL2-zzVRXh3Hf3QizaQI61El4',
  },
  5: {
    name: 'SpaceBud #5',
    traits: ['Belt'],
    image: 'ipfs://QmSM77ix4Bi8FKuEWBjJiuYQjndMmMCZd6xvLW8wPKpUnm',
    type: 'Ape',
    arweaveId: 'Pg8cbVggD9NBf87ZmSL09BM9giBiEE8-OC7gp2bsj5U',
  },
  6: {
    name: 'SpaceBud #6',
    traits: ['Chestplate', 'Belt', 'Snorkel', 'Watch'],
    image: 'ipfs://QmaTMt1LmNwfNN1yzPCsBgE3RBvhRg185YmG97Q5ZYkuHy',
    type: 'Tiger',
    arweaveId: '0kK0TFYxGTxp97YKAS4zBxYfOZ8C87uJxI8daCQJtYQ',
  },
  7: {
    name: 'SpaceBud #7',
    traits: ['Belt', 'Wool Boots'],
    image: 'ipfs://QmXPAF2ej9rKsyz4Y9p7RySXK3fuVX1t6YNdFLrXxMZBKU',
    type: 'Robot',
    arweaveId: 'UctB-TC32e6W0JQ5JNTCysjp1YuzPe_3aWB_6FR5NWw',
  },
  8: {
    name: 'SpaceBud #8',
    traits: [],
    image: 'ipfs://QmdzSx6epCsGaoCAaTByXKVyoLU9HGyXrAq8Vg1MeRGivf',
    type: 'Ape',
    arweaveId: 'SzkGhgBfYrM-jxoZjMjW5zacVBs7yZVk5vte2AKpCeY',
  },
  9: {
    name: 'SpaceBud #9',
    traits: ['Chestplate', 'Belt'],
    image: 'ipfs://QmShVWZ5PgfQ3PWhxLhm5AA6Ugw8pAJrHaYdmGC6LAFC4z',
    type: 'Dog',
    arweaveId: 'YZAcPYVFx1YuYZNzHhnd5-bb25ouTdvhbSzpddewx0s',
  },
  10: {
    name: 'SpaceBud #10',
    traits: ['Chestplate', 'Belt', 'Covered Helmet'],
    image: 'ipfs://QmYucGgd5cBizjfTk8KpnkaDDeHh7zr7K1qDT3u2L8f3Vr',
    type: 'Frog',
    arweaveId: 'BBPQOK_TUSy184_BSzGW7mmW6FVwVl2LoOPpr-xDMaE',
  },
  11: {
    name: 'SpaceBud #11',
    traits: ['Camo Suit', 'Chestplate', 'Belt'],
    image: 'ipfs://QmetCkZpyhRWfDPXhf5X4qAQnS7evhZa3qCm8DfZDM28Zq',
    type: 'Dog',
    arweaveId: 'vKD9OvnJ54hb7uWO7vL6cT2rSF307KyRpB7-kT3FOw8',
  },
  12: {
    name: 'SpaceBud #12',
    traits: ['Chestplate', 'Belt', 'Covered Helmet', 'Cardano'],
    image: 'ipfs://QmfKksNPq5bsYGVam4QJGoCERC8jxtr2DVFccTkzV5vKLp',
    type: 'Ape',
    arweaveId: 'aqHaoCZFTkpOzacYBceLi8gAvgk8mEHBKWsSSnTMz7g',
  },
  13: {
    name: 'SpaceBud #13',
    traits: ['Special Background', 'Belt', 'Covered Helmet', 'Wool Boots'],
    image: 'ipfs://QmU7CmCT3cqZ3jd2NFhWDc5mSK2jYFJCKVJPbNbPA9wNqn',
    type: 'Ape',
    arweaveId: 'MpVUdgrEwxlr6S1ZB8bWJ1V1jOEQ912hfSgKROc8P_4',
  },
  14: {
    name: 'SpaceBud #14',
    traits: ['Star Suit', 'Chestplate', 'Belt'],
    image: 'ipfs://QmX62KiNG5MNfoTNgzYDVuCxXM9FDbFt4qvZ2L3a8NyJ2E',
    type: 'Ape',
    arweaveId: 'Q0WwV3VfyK0WV8X9Y5QDok55jBKXdkmdEVchqtHlNhQ',
  },
  15: {
    name: 'SpaceBud #15',
    traits: ['Chestplate', 'Belt'],
    image: 'ipfs://QmaFfVsS1dNLGmUPudNo3rfqbN1RCdc5yptMFn7UQCgDdU',
    type: 'Robot',
    arweaveId: 'jE91h9zj1q2cOvqaO9nSxMbZQRMsfvNbDIcSr_WoNbA',
  },
  16: {
    name: 'SpaceBud #16',
    traits: ['Star Suit', 'Chestplate', 'Belt', 'Covered Helmet', 'Flowers'],
    image: 'ipfs://QmWiR9mEfUsRp66dFLEzuNPJBkA5AVpK8agp63dWLLXF2V',
    type: 'Frog',
    arweaveId: 'bWuaNT18Pl3dxHd1ViacxRn0v20VIa77FXULlld8D7A',
  },
  17: {
    name: 'SpaceBud #17',
    traits: ['Belt', 'Sun Glasses', 'Watch'],
    image: 'ipfs://QmXK6eoVWTwa2y4rRVQpNUnGnBk8Nh1RWfZTpiqZuqzvgP',
    type: 'Dog',
    arweaveId: 'bN941Qf9CbyvxCwrpFyn_6cZNt4pqpscpfSqwleuD6E',
  },
  18: {
    name: 'SpaceBud #18',
    traits: ['Star Suit', 'Chestplate', 'Belt', 'Bazooka'],
    image: 'ipfs://QmWdwh9yk1MVLfPANKDY5a9yZtPkPv1Ts6iNzRVRNx5N9w',
    type: 'Bear',
    arweaveId: 'W6-M8hoZsYhXFXK8aaQBN0FbsFSt12yNyjuM6Qgs3ow',
  },
  19: {
    name: 'SpaceBud #19',
    traits: ['Covered Helmet', 'Sun Glasses', 'Wool Boots'],
    image: 'ipfs://QmNdia1Zk7VjsjoQ4ttD4psG1AoTeJVNf4ZDRLnzk7ZCkU',
    type: 'Bear',
    arweaveId: 'ckU8NbYTH3ifBFRa2cDIPn6VCnVGEL7mxhU0qMKdwA4',
  },
  20: {
    name: 'SpaceBud #20',
    traits: ['Belt', 'Covered Helmet', 'Sun Glasses'],
    image: 'ipfs://QmS7oa7CGD7wJhbegD891d3pExNbQdnQ8tjKvp34oPyP7K',
    type: 'Cat',
    arweaveId: 'YIWkbE4qPPgUdx2NNtBDBViUhwenKEKAvUq7UkvOI3s',
  },
  21: {
    name: 'SpaceBud #21',
    traits: ['Chestplate', 'Belt', 'Jetpack', 'Sun Glasses', 'Amulet'],
    image: 'ipfs://QmaA73et5Qekw1vuyxZ9rR4cn4uPR5XrRyDHxJkrF5Sg3r',
    type: 'Tiger',
    arweaveId: '3Zm3wxolRGHjh7Yr6un_EddGkrzFVxuNMA4wrxtyy0c',
  },
  22: {
    name: 'SpaceBud #22',
    traits: ['Special Background', 'Chestplate', 'Belt', 'Pistol'],
    image: 'ipfs://QmWjNsrxvdSvd3EnW4bk9DcLteX8NJEjH5z4mFpC5DdrEE',
    type: 'Parrot',
    arweaveId: '6OjJ0M7GkHfXLuCaQEf5IRMWS3bN-d1pFLtn0c06510',
  },
  23: {
    name: 'SpaceBud #23',
    traits: ['Amulet', 'Belt', 'Covered Helmet', 'Anchor'],
    image: 'ipfs://QmaY3Mc1wGfgRMMX2MZENiuSuXUdJ5ZasKMLZQoobLZqSV',
    type: 'Parrot',
    arweaveId: 'IYIk2IM-VukBzS7z6GWqcKXWuXHNbFfvPrb3SNBgF68',
  },
  24: {
    name: 'SpaceBud #24',
    traits: ['Chestplate', 'Belt', 'Covered Helmet', 'X-Ray', 'Harpoon'],
    image: 'ipfs://QmULzNx69WVv7VKGVkUnf2ULkLx2gvpKVXEY6HowiWDjc8',
    type: 'Dog',
    arweaveId: 'JSywhDaFRugv13FtKep5Xxfelxd-n53uKr-lzdB5AQs',
  },
  25: {
    name: 'SpaceBud #25',
    traits: [
      'Special Background',
      'Star Suit',
      'Chestplate',
      'Belt',
      'Binoculars',
    ],
    image: 'ipfs://QmYvHVxNfegto3pzWLnVjTpPGguHEGL5M4LXjnhCXdKkJo',
    type: 'Arcane',
    arweaveId: 'a9tQtkoPni0mG8WQN1HxFZAbtpQ60J2aKF5meWfV_AU',
  },
  26: {
    name: 'SpaceBud #26',
    traits: ['Chestplate', 'Belt', 'Covered Helmet', 'Eye Patch'],
    image: 'ipfs://QmX4RNNxFgbk2zkFTxdXRWfPMAce3ZxaWoa76T4MDLdK6p',
    type: 'Lion',
    arweaveId: 'i9K5xaTBj9RRCcvvlzA4wilrv-JUZVESR_wuzBOoECI',
  },
  27: {
    name: 'SpaceBud #27',
    traits: ['Chestplate', 'Belt', 'SPO'],
    image: 'ipfs://QmYMVfKMZEd2goMH275WsR8xhghHVPUeXCs2tPTZLh6FCC',
    type: 'Elephant',
    arweaveId: 'TtX0jmuAeFKOjwrL7ovTgPPDmX8EcwM_GhWdFI2Jq6A',
  },
  28: {
    name: 'SpaceBud #28',
    traits: ['Chestplate', 'Amulet', 'Belt', 'Umbrella', 'Covered Helmet'],
    image: 'ipfs://QmXx2ZqMwy8oRV9UYHeP9RX2v4kMV1FYb8mTswsW51iYZy',
    type: 'Frog',
    arweaveId: '-0Oy_j2m7_vn1jun_vFY1Ci5YfAiesndm8ExTKMJYOQ',
  },
  29: {
    name: 'SpaceBud #29',
    traits: ['Chestplate', 'Belt'],
    image: 'ipfs://QmSYao5RNppz1fXXtu76h3aMN3mVvxJVoQ2a8eerpQm9ih',
    type: 'Tiger',
    arweaveId: '8PBj89Q8SlpShA5wGj-5M_dymzS4sHhPrLaSkbyN5xM',
  },
  30: {
    name: 'SpaceBud #30',
    traits: ['Chestplate', 'Belt', 'Cardano'],
    image: 'ipfs://QmbmKPh4VX3GWXGsQ3y3EPj2m6NjgxNmFcrfxpCAbhrzP5',
    type: 'Tiger',
    arweaveId: 'awe-HB7s33xVoD4tXebsq6hJjKlz6H2zKKEz-4EJX_w',
  },
  31: {
    name: 'SpaceBud #31',
    traits: ['Camo Suit', 'Chestplate', 'Belt', 'Covered Helmet'],
    image: 'ipfs://QmW8MczooYq1WkBxAyVjZZUPoBXV5ZGTJc8L28Y42NC1cx',
    type: 'Cat',
    arweaveId: 'KFtX1SVh1SoZtZJ3WnWOiPjA_pv_QOvKjPnsxbPgM_k',
  },
  32: {
    name: 'SpaceBud #32',
    traits: ['Star Suit', 'Chestplate', 'Belt', 'Arc'],
    image: 'ipfs://QmZNnV215XqcpC9qAEAcrTHMcGQAU9Q3U9C62rmH5wzZ5d',
    type: 'Robot',
    arweaveId: '1hIm1WJ1gqXvUPkBQAcf9yiEXlJKmtNuN_oByFKB6AI',
  },
  33: {
    name: 'SpaceBud #33',
    traits: ['Camo Suit', 'Chestplate', 'Belt'],
    image: 'ipfs://QmTRf1tkHyvkEskj8iwz6GH6apt4RUhoaP3wjsxDJDHwHp',
    type: 'Ape',
    arweaveId: 'E2f8kNfliCavzOkwBdOGHBilBTdiqc6EEgbAwX3pssQ',
  },
  34: {
    name: 'SpaceBud #34',
    traits: [
      'Camo Suit',
      'Chestplate',
      'Belt',
      'Jetpack',
      'Covered Helmet',
      'Flowers',
    ],
    image: 'ipfs://QmU5DGq7otnYQgqrCeFaHkY2PLWf8R9ZLhjb77hCq1qfnF',
    type: 'Alien',
    arweaveId: 'gPe0GuXVpgOzzzSeN95k-yxbxxVNjR74p6jzwRTMleM',
  },
  35: {
    name: 'SpaceBud #35',
    traits: ['Chestplate', 'Eye Patch', 'Flag', 'Axe'],
    image: 'ipfs://QmYX2z1gFFsQRwgjRrEPUH6FkB2XwnVp6DkEYprrdG4VbT',
    type: 'Bear',
    arweaveId: 'mI1wyQPmKXsYh2Z42u0T-bal5J1YyyL3jj0nqMLZwC8',
  },
  36: {
    name: 'SpaceBud #36',
    traits: ['Belt', 'Covered Helmet', 'Sun Glasses', 'Amulet'],
    image: 'ipfs://Qmb9TXZbwbvP5ZMAR78QXuoVzMh5sNFbxU3Upe2u1Lse6g',
    type: 'Robot',
    arweaveId: 'rIWCVdlAV8kQNnxFAhEhOiOUw-FWQbME6YWsGUMwsMg',
  },
  37: {
    name: 'SpaceBud #37',
    traits: ['Belt', 'Covered Helmet', 'Flag', 'Axe'],
    image: 'ipfs://QmfQ86pdfqgJanSb4DCeoy42XPeCLz694DBKBaDfBcrBGb',
    type: 'Robot',
    arweaveId: 'QHpEDp1JKVZZ3yudGRikC5Qa--lRr8uvcMSQJQhYOZA',
  },
  38: {
    name: 'SpaceBud #38',
    traits: [
      'Star Suit',
      'Chestplate',
      'Amulet',
      'Belt',
      'Backpack',
      'Covered Helmet',
      'Eye Patch',
    ],
    image: 'ipfs://QmPYyFDsWNSL77QYpuxCdKXWzp1w72o16gkxBNomp5jquW',
    type: 'Dog',
    arweaveId: 'PywKB3qdIWdJ0cxMRjl2n0O_t62JjyDEKrNMRDyl4kM',
  },
  39: {
    name: 'SpaceBud #39',
    traits: ['Wine'],
    image: 'ipfs://QmbNbLV2Qtg6imHqi3EC2ML13XG5c5fmbqfhzfTRxA8Kjy',
    type: 'Dog',
    arweaveId: 'SGg1eFU-rF2Yx5pLJyResMg-WKQJlrmwPYmk7YbgJEM',
  },
  40: {
    name: 'SpaceBud #40',
    traits: ['Star Suit', 'Chestplate', 'Belt', 'Snorkel'],
    image: 'ipfs://QmRzjVh8B91JApF4XntNhLosZuUYQfo6ckcSBqCGLL944o',
    type: 'Cat',
    arweaveId: 'Ny40uONyFM2jlnb7d3ChoLwg2c8yDrLRM1Gkt3fVobs',
  },
  41: {
    name: 'SpaceBud #41',
    traits: ['Camo Suit', 'Belt', 'Covered Helmet', 'Flag'],
    image: 'ipfs://QmUTR3QE49HG2e2LTURb1HG2qaEYJtaUjoAhYmzXDbdB2D',
    type: 'Lion',
    arweaveId: 'ThKT5gGmixTVHFgiiFilX0dsUiCha-dtEvq-jqeRzb8',
  },
  42: {
    name: 'SpaceBud #42',
    traits: [
      'Special Background',
      'Star Suit',
      'Chestplate',
      'Belt',
      'Covered Helmet',
      'Anchor',
    ],
    image: 'ipfs://QmNNytE4NauP2xFMhUrHh5wY3NQSwdoBr6ENhyxz6dohPD',
    type: 'Ape',
    arweaveId: 'ODYbAq2RFGzVzXmoNDZ7fZ5pMuwfU_Mkn19sg_Kaggc',
  },
  43: {
    name: 'SpaceBud #43',
    traits: [
      'Special Background',
      'Star Suit',
      'Chestplate',
      'Belt',
      'Sword',
      'Amulet',
    ],
    image: 'ipfs://QmZ61H8TuhyorUstXtqTBHkQDE12VwJtcs7WAhZ2814uJa',
    type: 'Tiger',
    arweaveId: '6Ygj0J2yphxEJnbRybwNSFnhvV8r1UYQqCPSCWWTzRI',
  },
  44: {
    name: 'SpaceBud #44',
    traits: ['Chestplate', 'Belt', 'Pistol'],
    image: 'ipfs://QmUnEQEJVfQp2T798CNx65FHsi2gHNJA87CETq6a1ndDDj',
    type: 'Cat',
    arweaveId: 'VocazyR01Ud8TERdIVIrbB5t5M4sFlddusxp8My_CiU',
  },
  45: {
    name: 'SpaceBud #45',
    traits: ['Chestplate', 'Belt', 'Backpack', 'Sun Glasses'],
    image: 'ipfs://Qmc2qrhZJWHDKYaE9iJuxkbbt94hCLcZwvv4Md1iPNH4AY',
    type: 'Cat',
    arweaveId: 'foUMv-vv7QSFi9WxbUvk8TRHqioiKMmJsqLeQhrVU9s',
  },
  46: {
    name: 'SpaceBud #46',
    traits: [
      'Chestplate',
      'Belt',
      'Backpack',
      'Covered Helmet',
      'Wool Boots',
      'Pistol',
    ],
    image: 'ipfs://QmdCy2fVGp3SWgkdAD6pfyJKGUrp73WcQjrFE1QHFs6JWt',
    type: 'Bear',
    arweaveId: 'wr45pYK80DWdDEY0Ma-b7Ndd80FKFMb3G4ksI3K9iXk',
  },
  47: {
    name: 'SpaceBud #47',
    traits: ['Chestplate', 'Belt', 'Covered Helmet', 'Cardano'],
    image: 'ipfs://QmeRjidTqECcsfMpH2R9mvTwkWoWY9fp2pPikHGm88iSdb',
    type: 'Arcane',
    arweaveId: 'v9tnJsj-3sw3OLOm9iHr8R5WjWGCNnwWIqpu2O3AQ7M',
  },
  48: {
    name: 'SpaceBud #48',
    traits: ['Belt', 'Covered Helmet', 'Jo-Jo'],
    image: 'ipfs://QmbKvKWrCB2gB2kTH87HpWi6oi1db6HYu94rxp36DdDAhg',
    type: 'Frog',
    arweaveId: 'WUnz2AhUTukrIOAKGZSblSrz1KWJQYsIMgFmzaVbaYU',
  },
  49: {
    name: 'SpaceBud #49',
    traits: ['Chestplate', 'Belt'],
    image: 'ipfs://QmZBJs2V8zbgbnMosGk56HLS2TKx4pfWT7JuuQdYAabzUm',
    type: 'Frog',
    arweaveId: 'ah4MBWQGQPJGaq2wbcl6IkTeIlpn_Js3MpzgU6YLylw',
  },
  50: {
    name: 'SpaceBud #50',
    traits: ['Star Suit', 'Chestplate', 'Belt', 'Cardano'],
    image: 'ipfs://QmcdpMsTti7LA8BV8J1bwVhKxoVSeu7R95JVUs3mMGUjVa',
    type: 'Robot',
    arweaveId: 'YdmXOYAfjqwxlLuxnS9jM8qKD3XxbGD1-rBPC452dEs',
  },
  51: {
    name: 'SpaceBud #51',
    traits: ['Chestplate', 'Belt', 'Covered Helmet', 'Axe'],
    image: 'ipfs://QmbHYo2zXfUJdGSMmUPiQyT7mXkXBgp8iC9LYnsJgnDMLS',
    type: 'Ape',
    arweaveId: 'rz53rNVWerDFA2P4JkXBtfPDpzKaoSM9_ztZF6dLFbw',
  },
  52: {
    name: 'SpaceBud #52',
    traits: ['Star Suit', 'Chestplate', 'Belt', 'Covered Helmet', 'Arc'],
    image: 'ipfs://QmabjquQ59ufJfY7zApPuUVhc5HKUnrnnmDsCw2mvfY1G3',
    type: 'Cat',
    arweaveId: 'jkxxIpzrg0qQgm9Wkp-EQRACAEaw5R-gq3BGN54bdHs',
  },
  53: {
    name: 'SpaceBud #53',
    traits: [
      'Chestplate',
      'Amulet',
      'Belt',
      'Covered Helmet',
      'X-Ray',
      'Blaster',
    ],
    image: 'ipfs://QmTUyv6rqZJ6hAt3vd8B6uTA5aJfSv93QpmCPEgfrsTBRt',
    type: 'Alien',
    arweaveId: 'fyAZv_7F9zjC_McHAqRsYPQGk3ViXmw4pLl1d_-6dXI',
  },
  54: {
    name: 'SpaceBud #54',
    traits: ['Chestplate', 'Jetpack', 'Covered Helmet', 'Pistol'],
    image: 'ipfs://QmbUHAqnv9ghgRLRSAv4EXRRm5m5XrR2AG3oSjt8xwVXLm',
    type: 'Parrot',
    arweaveId: 'WulBUuL1DXLcstmQfvgrf3nCwKLkeaoz6hYAK7AYOgo',
  },
  55: {
    name: 'SpaceBud #55',
    traits: ['Chestplate', 'Belt', 'Harpoon'],
    image: 'ipfs://QmQmpPJW5rBZLNBttd165M1a2A59E5syPmPgikc2fFYxev',
    type: 'Robot',
    arweaveId: 'jjsJAe5ufAgzYW81zDdTwZsW-MjMrmh800070CgI8H8',
  },
  56: {
    name: 'SpaceBud #56',
    traits: ['Belt', 'Covered Helmet'],
    image: 'ipfs://QmPqJ1A3gttkY93AEUfG4yM7Kr8LpftZvN4QKKqG3ETGgH',
    type: 'Dog',
    arweaveId: 'XiUhRq3H6TNM-tYTtQwlUAMoWjWA7MGsV9b-cHaxXJA',
  },
  57: {
    name: 'SpaceBud #57',
    traits: ['Chestplate', 'Belt', 'VR'],
    image: 'ipfs://QmYPjLWYThPg8dgVAELonNA4yWJuqTQEDCkF5vLXqKB9rh',
    type: 'Arcane',
    arweaveId: 'e5XqiQ--YBSP4VM7DRBdLxXjSmTfyUT5fbKgD1LwzUQ',
  },
  58: {
    name: 'SpaceBud #58',
    traits: [
      'Camo Suit',
      'Chestplate',
      'Belt',
      'Covered Helmet',
      'Watch',
      'Cardano',
    ],
    image: 'ipfs://QmRsZCdGNtPFn872Ev62qSJUybzUahBxcfGK5cNHo92PqN',
    type: 'Ape',
    arweaveId: 'PlnGF2tvHEIzRg3j_cATpSfq0kZiRR9wkeCq8EOe9p8',
  },
  59: {
    name: 'SpaceBud #59',
    traits: ['Star Suit', 'Chestplate', 'Amulet', 'Belt', 'Arc'],
    image: 'ipfs://QmZmWSB84h6UHWd1ZsYnvEBFA4Af1kBd6t5yrhLbjXFZ5e',
    type: 'Ape',
    arweaveId: 'Z_yFZE5IG7590VDmguMjkNBUbZ6JUHFp403aNN5P7FI',
  },
  60: {
    name: 'SpaceBud #60',
    traits: ['Chestplate', 'Belt', 'Blaster'],
    image: 'ipfs://QmUnzLZBj9Uxxiaz4WiYHWJQgGf8NFefKdABVMYTBDNviP',
    type: 'Elephant',
    arweaveId: '1kYIeiZi8GWJkx0neAkNp4I9Orp_dCwq70f-yCvcuJU',
  },
  61: {
    name: 'SpaceBud #61',
    traits: ['Star Suit', 'Chestplate', 'Belt'],
    image: 'ipfs://Qmar3Xht4BXb3RXSPnzTngak7RGUnF2uygF2RRGFXs8FH3',
    type: 'Dog',
    arweaveId: 'kYTJZgxglnGykdL83GaGlpF4cIaI1jg7FipJcLJJC8o',
  },
  62: {
    name: 'SpaceBud #62',
    traits: ['Belt', 'Flowers'],
    image: 'ipfs://QmZPmVJzp257oHDTz5T67KD35mm6C5wY4a7kVqvu57n53E',
    type: 'Parrot',
    arweaveId: 'O2_GJmSf3_lLKjeyVRSLe3oWLKCe0eVGUoxQVP8sPn0',
  },
  63: {
    name: 'SpaceBud #63',
    traits: ['Chestplate', 'Belt', 'Backpack', 'Eye Patch'],
    image: 'ipfs://QmQco9iGFBiq1LfDSqBSXVAf6zYgubMdXfbjkojZ3jE6Zh',
    type: 'Cat',
    arweaveId: '9CsPMoCbDZuJUNim6lfiKQzDT3x1Gv5Yf1Yyccbefjw',
  },
  64: {
    name: 'SpaceBud #64',
    traits: ['Belt'],
    image: 'ipfs://QmWvoF9GNp4t4DcV73ajqx7HomFJhSjtDpW1zTsZuZrWq2',
    type: 'Tiger',
    arweaveId: 'pc9BgVNky_EpvlZ3MJPf6ZJxj3amW-82XUkNDZJ8a54',
  },
  65: {
    name: 'SpaceBud #65',
    traits: ['Chestplate'],
    image: 'ipfs://QmfMnNgtUZTssVshUzhzuV3mt3wxUYUxPtWV2ZSufKj1T6',
    type: 'Tiger',
    arweaveId: 'BloOdEmq_c5ttS9rHLjrBdHwJkI23wHFCvLq7Ca4KtE',
  },
  66: {
    name: 'SpaceBud #66',
    traits: ['Chestplate', 'Belt', 'X-Ray'],
    image: 'ipfs://QmZRvNupm3k3BdX3s6U47XVJTMFoq8X4Su8eNgEDuB3o8X',
    type: 'Bear',
    arweaveId: 'DWRHP27iwAFQ9A3MVPSeS4kuUAd5_ORoQUvUVllsUx8',
  },
  67: {
    name: 'SpaceBud #67',
    traits: ['Chestplate', 'Belt'],
    image: 'ipfs://QmWNP87nazVcRjRgkwbNeWP3mAUKG9H1oGUuKeKgr9ARVV',
    type: 'Arcane',
    arweaveId: 'LBnN7znyzHNTQfjgP5JQ3F6RNH7OJknNFJfOagcPR6o',
  },
  68: {
    name: 'SpaceBud #68',
    traits: ['Belt', 'Binoculars'],
    image: 'ipfs://QmdkbddkiBYAMEh5VDXbjaoyUy2i5yikiYxQ6AXg6zESnL',
    type: 'Arcane',
    arweaveId: 'mstYN93IidbhkHQrPoE22G3VDq2xQPrxnTM2mHFIyHQ',
  },
  69: {
    name: 'SpaceBud #69',
    traits: ['Belt'],
    image: 'ipfs://QmWLMbHoYJvcRLbozgeaziF2GPnqoaRoDFomTL4qQCABsZ',
    type: 'Cat',
    arweaveId: 'jOhjDO2su8PqxWxNHq9Yx3K5oz-1tY7K76ddgYN8dLM',
  },
  70: {
    name: 'SpaceBud #70',
    traits: ['Special Background', 'Chestplate', 'Amulet', 'Belt', 'Snorkel'],
    image: 'ipfs://QmcAk4oT3AtmUZeP3FQyU8b21achrCffMNxjuzr9QQTp4C',
    type: 'Tiger',
    arweaveId: 'mq91CKmMvz_uwqgUO9BkNjxrdEGQeR_xGzHS9XAz12M',
  },
  71: {
    name: 'SpaceBud #71',
    traits: ['Belt'],
    image: 'ipfs://QmUSDx6Q8RyDGr7pa9Kgy4rmvbWDZHYpcR3igRrHhXT2jL',
    type: 'Parrot',
    arweaveId: 'CnfhZc-MrNipfeM62NQr3pvYK59G9PykdDaeNhHBFh8',
  },
  72: {
    name: 'SpaceBud #72',
    traits: ['Chestplate', 'Belt', 'Covered Helmet'],
    image: 'ipfs://QmZWeigModsHTPy9sZKDKRxD3rCzLUojxWoGjSqDjdaBCd',
    type: 'Alien',
    arweaveId: 'uwCpndRQdjksoofSWbM0LyeRsGO79HiL17M-y_TF7f8',
  },
  73: {
    name: 'SpaceBud #73',
    traits: ['Star Suit', 'Chestplate', 'Belt', 'Covered Helmet'],
    image: 'ipfs://QmWVN8SgKh229PWGGVAoQJYEDodwq8jAgPU3ZszPXQMEgU',
    type: 'Frog',
    arweaveId: 'fvsXjmpDp01aOC4qHzP_UrafeZyFyIu5sfpszNjld8o',
  },
  74: {
    name: 'SpaceBud #74',
    traits: ['Chestplate', 'Amulet', 'Belt', 'Axe'],
    image: 'ipfs://QmXfWD7cFL1xUjfJV5VmUKf3AnrWncVdFj93hUFYAPFB1S',
    type: 'Cat',
    arweaveId: 'JnkOl-np8phNk4g_zjmUnSi16IM15x_LQPajC53lzLA',
  },
  75: {
    name: 'SpaceBud #75',
    traits: ['Chestplate', 'Belt', 'Covered Helmet', 'Ski Goggles', 'Revolver'],
    image: 'ipfs://QmfVHUjZCe6mw2xAH2r3jNxpZUECpktga64ZQBBMEpSrkR',
    type: 'Alien',
    arweaveId: 'lggdxmaAnynWmUwiRaEXOWM0kAJEoehnoeTEc1n7YWk',
  },
  76: {
    name: 'SpaceBud #76',
    traits: ['Belt', 'Covered Helmet'],
    image: 'ipfs://QmcgCNUtioow3SK6U5U6GXVFJGqNeRFH1RvHzYEG8t41RG',
    type: 'Arcane',
    arweaveId: 'zhe32t4IR2SvVi-mqDGRjsgQM2m0scgSiVki1c7C2P8',
  },
  77: {
    name: 'SpaceBud #77',
    traits: ['Star Suit', 'Chestplate', 'Belt', 'Flowers'],
    image: 'ipfs://QmYJEg67cB8HkkAEx51rfRc4pEtsCgqsVF5vzct3RLRfWc',
    type: 'Bear',
    arweaveId: 'kAmpQ7bOCnWcaN_4Zti60RVJDkeFO8asniZZ3FIZGs4',
  },
  78: {
    name: 'SpaceBud #78',
    traits: [
      'Special Background',
      'Star Suit',
      'Chestplate',
      'Belt',
      'Covered Helmet',
      'Snorkel',
    ],
    image: 'ipfs://QmTDrGSmzEtHQgf8MWmDJN3pKaLjUqvVdSXnH9a7oWw5tJ',
    type: 'Cat',
    arweaveId: '8wRt1TNvLn-k5tB5Aa2sBm1kMs0enAjQ7YLj5c7nqBI',
  },
  79: {
    name: 'SpaceBud #79',
    traits: ['Star Suit', 'Chestplate', 'Belt', 'Covered Helmet', 'Watch'],
    image: 'ipfs://QmUPuXh9EhDS26UeyufXTSGMCv8ivmud8gowDdqZZzqZnk',
    type: 'Dog',
    arweaveId: '89vCfql3fJJNonFcL8n5Nqa5KqWdLLrKdbzz0UCEADQ',
  },
  80: {
    name: 'SpaceBud #80',
    traits: ['Belt', 'Covered Helmet'],
    image: 'ipfs://QmcJyVdURXGzroWcCrMtuSUXGCmNFWj7DUNPwGGZ8jkGjN',
    type: 'Alien',
    arweaveId: 'E9q1UtTgzH7692g4HPHEWsoA_WbcYYEn5QhyxyrGbQ4',
  },
  81: {
    name: 'SpaceBud #81',
    traits: ['Chestplate', 'Belt', 'Ski Goggles'],
    image: 'ipfs://QmRcsCL9TfSn4Peou2jMmt1SDhdV91k3RQshDMN35AHnke',
    type: 'Ape',
    arweaveId: 'e7evAWkJnmeqVyfTFRwicw-ao8EEo8Ftc2nEtfFjy-I',
  },
  82: {
    name: 'SpaceBud #82',
    traits: ['Star Suit', 'Chestplate', 'Belt'],
    image: 'ipfs://QmanWzgkkKG5QV4NE38TyEZ5oqTPLBsLW91VBG9hWYjSM8',
    type: 'Parrot',
    arweaveId: 'tbWA4F2dm8W46DXjH8PS1NJAd7S-hjZMV665fzsm1N4',
  },
  83: {
    name: 'SpaceBud #83',
    traits: ['Belt'],
    image: 'ipfs://QmdziPk2LULo5gLn9haG6WVZNJqmhtKDzPNeK3bRAQT7nA',
    type: 'Tiger',
    arweaveId: 'pEIkXmNTo0H1Se1rQp-QvJAd1PgaTyfYvmNzLNs2m70',
  },
  84: {
    name: 'SpaceBud #84',
    traits: ['Special Background', 'Chestplate', 'Belt', 'Covered Helmet'],
    image: 'ipfs://QmSPvA6AvMHCcm13CgKm9RXSrcRJZDBMeMmjWh9Q8TtEkC',
    type: 'Dog',
    arweaveId: 'lQoZpjFycIMXaj7gusgB2TahxgR_ZP8zmNIpVkvIpGs',
  },
  85: {
    name: 'SpaceBud #85',
    traits: ['Chestplate', 'Covered Helmet'],
    image: 'ipfs://QmSobhwZX8nJY6dFQHw6zHHJjeCt5A4jMrYNtzxEsHe8X8',
    type: 'Arcane',
    arweaveId: 'ySZe78LcphIrqVATaEO8UlvJsk5fmKrjzGigGhRmiWg',
  },
  86: {
    name: 'SpaceBud #86',
    traits: [
      'Special Background',
      'Camo Suit',
      'Chestplate',
      'Belt',
      'Covered Helmet',
      'Ski Goggles',
    ],
    image: 'ipfs://QmQGFgXWyr4psHNJNsJNaQ7TCqtYVDPWHnFgToxHY6xxBW',
    type: 'Cat',
    arweaveId: 'GjnA2nr5XDu7c3QlkksAONH5magH--BIKw3VDzK0NvU',
  },
  87: {
    name: 'SpaceBud #87',
    traits: ['Chestplate', 'Belt'],
    image: 'ipfs://QmeAthmcXpHF7cLiCALHkZf2qrnAHcpRLEkQkPQMQKyso9',
    type: 'Elephant',
    arweaveId: 'AMEY2G73xA2n6CLwLm0K9m-ralzKImlud_O9X3ZoSpA',
  },
  88: {
    name: 'SpaceBud #88',
    traits: ['Special Background', 'Chestplate'],
    image: 'ipfs://QmQqcSmtL6dVscACNNXJjftYVsMTYVqH6ZUG72JmWqHXRs',
    type: 'Ape',
    arweaveId: 'XFoaY-7J0Szb7d9h_-jvjAT1i2pTZ0X_eZlmtu3AIP0',
  },
  89: {
    name: 'SpaceBud #89',
    traits: ['Chestplate', 'Belt', 'Candle'],
    image: 'ipfs://QmSTFpT9j4AUL86QNsxQDDqGW1gQd4cZQenxzkSqQcigsg',
    type: 'Cat',
    arweaveId: 'Z2LHHrqK5pJSu44cCtjrp7JelOlcvxxEnIQYaD42gHg',
  },
  90: {
    name: 'SpaceBud #90',
    traits: ['Camo Suit', 'Chestplate', 'Belt', 'Pistol', 'Hockey Stick'],
    image: 'ipfs://QmQnkCGDUs2sUYv6wHDFMuoyc4GHyANUhvSnFKynNHp6CQ',
    type: 'Dog',
    arweaveId: 'tomgXRpD_9dWpFwZo7VnrKF68YkkpKCDoPMcQsm22jo',
  },
  91: {
    name: 'SpaceBud #91',
    traits: ['Belt', 'Covered Helmet'],
    image: 'ipfs://QmeM3k8K6wb4E2e17gYeGz4Gevx38SZc4Cq9vWC5C4x3De',
    type: 'Frog',
    arweaveId: 'IjCztkZ9ZWiVADrCOhTYBsslvihm3aKKT7I-OtGoDro',
  },
  92: {
    name: 'SpaceBud #92',
    traits: [
      'Camo Suit',
      'Chestplate',
      'Amulet',
      'Belt',
      'Covered Helmet',
      'Sword',
      'Axe',
    ],
    image: 'ipfs://QmdztNQNVrYjEFhsyxWXAxNXanKt1JXP9PNPznJuXC5z5W',
    type: 'Alien',
    arweaveId: 'ydGdvfH8FWYibtk2RlBArbleh06KtLgM4Oa5lUpnAaY',
  },
  93: {
    name: 'SpaceBud #93',
    traits: ['Chestplate', 'Belt', 'Covered Helmet'],
    image: 'ipfs://Qmc4ymCeaU2YXVpDZUHQpb3z8GrcEPvYJKtcR3yjR58KTm',
    type: 'Dog',
    arweaveId: 'bEINBnr7Dmh1PXI09wLYTo2qxd52eB0UDIeP_N-NTwQ',
  },
  94: {
    name: 'SpaceBud #94',
    traits: [
      'Star Suit',
      'Chestplate',
      'Amulet',
      'Belt',
      'Ski Goggles',
      'Bazooka',
    ],
    image: 'ipfs://QmXuiFNwu7ZuKv5GSoTm82272WNJarSthvpZ1DFpghZhJH',
    type: 'Ape',
    arweaveId: '4-00tkeEZO0I1iQ-mST3P_rULurTWb51PEjmS_GZAM4',
  },
  95: {
    name: 'SpaceBud #95',
    traits: ['Special Background', 'Belt', 'Covered Helmet', 'Jo-Jo'],
    image: 'ipfs://QmbNPqhTPYpGVzZFJkXTLAYfuXcKaPtvwbuwrnF5SMxTfw',
    type: 'Dog',
    arweaveId: 'Iz9FWprEBn1gHIUgmxIsstFcr9sIPMytPeTbSqbVrJI',
  },
  96: {
    name: 'SpaceBud #96',
    traits: ['Covered Helmet'],
    image: 'ipfs://QmdCU2LVPL7q8MUfbiDZspkLSabS5BYM1KWcDHqkdoT3Hq',
    type: 'Bear',
    arweaveId: 'jKXAfCCA0TSvykK8tFgOp9NAInxrYE8No2ZWZPcCRvE',
  },
  97: {
    name: 'SpaceBud #97',
    traits: ['Special Background', 'Belt', 'Covered Helmet', 'Wine'],
    image: 'ipfs://QmVERc72FFA4VKmJxj6JReZQYBQY3AEP6g2wknue448Rvw',
    type: 'Cat',
    arweaveId: 'uCswTKuIcqTgXBC4B0IJOOKBiJcYI4XldfDXs2GtVpI',
  },
  98: {
    name: 'SpaceBud #98',
    traits: ['Camo Suit', 'Belt'],
    image: 'ipfs://QmNmPedfa2ftkzG8tVKLPoy7Q3qRSs1dRF7AKWqL2oVHMc',
    type: 'Lion',
    arweaveId: 'QneRPmwvD18ahItPw_tFXi8Q0hV_JwlQxT45LLvZWcY',
  },
  99: {
    name: 'SpaceBud #99',
    traits: ['Star Suit', 'Chestplate', 'Belt', 'Harpoon'],
    image: 'ipfs://QmWmHHhb2ts8vsRqoFyg3unVKK9j1cmQLmVpEtsAGFDmLY',
    type: 'Arcane',
    arweaveId: '0kN8jQ2ZmJsaJSnsYy6vFGfg5lLRdpoJRLiToTazypk',
  },
  100: {
    name: 'SpaceBud #100',
    traits: ['Chestplate', 'Belt'],
    image: 'ipfs://QmYoiS1TxmoCjrznKFXHCpMxm5kkKeKRdTFtCbN6FVDoy1',
    type: 'Dog',
    arweaveId: 'rDoM1rvZgfVut6TIRevn43WQTcxO5q2fJTRo0khzQ6M',
  },
}
export const categories = [
  'Elephant',
  'Fox',
  'Dino',
  'Tiger',
  'Cat',
  'Bear',
  'Arcane',
  'Frog',
  'Robot',
  'Alien',
  'Parrot',
  'Dog',
  'Lion',
  'Ape',
]

export const traits = [
  'Axe',
  'Belt',
  'Star Suit',
  'Watch',
  'VR',
  'Revolver',
  'Flowers',
  'Anchor',
  'Chestplate',
  'Covered Helmet',
  'Sword',
  'Ski Goggles',
  'Wool Boots',
  'SPO',
  'Special Background',
  'X-Ray',
  'Camo Suit',
  'Cardano',
  'Sun Glasses',
  'Bazooka',
  'Jetpack',
  'Amulet',
  'Pistol',
  'Harpoon',
  'Binoculars',
  'Eye Patch',
  'Umbrella',
  'Arc',
  'Backpack',
  'Wine',
  'Snorkel',
  'Flag',
  'Jo-Jo',
]
